dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - openjdk-8-jdk
      - g++
      - unzip
      - zip
      - wget

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.13.1/bazel-0.13.1-installer-linux-x86_64.sh
  - ./bazel-0.13.1-installer-linux-x86_64.sh --user
  - export PATH="$PATH:$HOME/bin"

script:
  - bazel build //test:cgrade_test