dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++
      - clang-3.6
      - wget

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.13.1/bazel_0.13.1-linux-x86_64.deb
  - sudo apt-get install ./bazel_0.13.1-linux-x86_64.deb

script:
  - bazel build //test:cgrade_test